### ISSUE TITLE
Install fails - com.sun.jdi.Bootstrap not available

### ISSUE THREAD

**Issue by pdoubleya** [prismofeverything/schmetterling#2] opened 2013-11-16 19:22 UTC
Hi

on lein run I get

```
Exception in thread "main" java.lang.ClassNotFoundException: com.sun.jdi.Bootstrap
```

This is on OS X, which may matter, because I'm guessing this is an issue of how CDT locates the tools.jar file. 

I searched around and could only find some older posts about this problem, which didn't help, e.g. 
https://groups.google.com/forum/#!topic/clojure/dJNt7mzeIGQ

tools.jar is present in the lib directory of my Java installation, and it contains the Bootstrap class. I assume that CDT may be trying to append to the existing classpath and building a path to the wrong location. Tips?

Thanks
Patrick

**Comment by prismofeverything** [comment] 2013-11-16 19:52
Hmm... I don't see anywhere in cdt that is explicitly looking for tools.jar by path, it simply refers to classes that are in tools.jar.  It seems like tools.jar is not in your classpath somehow?  Strange!

I'll look around for any hints.

**Comment by pdoubleya** [comment] 2013-11-16 19:55
I think tools.jar would normally not be on the classpath, as IIRC it includes tools aimed just at developers, not typical JRE users. There is likely no magic, I just have to figure out how CDT would like to locate it (or how I can easily manipulate the classpath in this case) though I am wondering why it works for you.

**Comment by prismofeverything** [comment] 2013-11-16 19:58
Based on this: http://stackoverflow.com/questions/7000578/tools-jar-not-on-classpath-anymore/7025824#7025824
and this: http://stackoverflow.com/questions/13544196/jre-system-library-missing-tools-jar

It looks like you may have multiple java installs and while tools.jar is in one of them, it is not in the other.  Possibly the difference between your system java and another java install?  

What happens when you run > java -version ?  Is it the one you expect?

And yeah, it looks like it comes with the JDK but not the JRE... it would be good to solve this as I'm sure others will have this problem!

**Comment by prismofeverything** [comment] 2013-11-16 20:41
Try copying tools.jar into your resources dir.  Does that work?  If so we just need to figure out why it doesn't find it normally.  

My output when running java -version if it helps is:

```
java version "1.6.0_37"
Java(TM) SE Runtime Environment (build 1.6.0_37-b06-434-11M3909)
Java HotSpot(TM) 64-Bit Server VM (build 20.12-b01-434, mixed mode)
```

**Comment by pdoubleya** [comment] 2013-11-16 21:05
I have more than one version of Java installed - currently, a 1.6, a 1.7 and a 1.8 release. The java home property is set using an OS X-specific tool called java_home - I do this in my Bash profile so that when I'm on the CLI I can select which JDK is "current". At the moment it's set to 1.7.0_45 and that's what java and javac both report. There is a lib/tools.jar in the path for that JDK.

If I create a dev-resources directory in the project (which appears to have been automatically added to the project classpath), and unpack tools.jar there, then on opening a repl with lein repl there are no errors reported - it finds the Bootstrap classpath. I can then lein run and attach to the schmetterling app via the browser (to caribou started separately).

This is an OK workaround for now - tools.jar is AFAIK very stable, and I only had to do it once. Still, I'd like to know what is failing. My guess is that something within the toolchain is looking for a version of Java and finding one of the older, unused ones from Apple (which I still have installed - not sure what, if any, OS X apps may fail if I remove it, so...). 

Thanks!

**Comment by prismofeverything** [comment] 2013-11-16 21:14
Awesome!  Let me know how it works out.  I have had some issues with attaching Schmetterling to Caribou started with

```
lein ring server
```

which uses jetty behind the scenes (something in nio eventually ends up closing the socket).  If you run into that use

```
lein run
```

to start Caribou (which runs with HTTPKit, which is better IMO anyway).

**Comment by noisesmith** [comment] 2013-12-04 19:38
I am failing to find com.sun.jdi.Bootstrap. I have no regular jre installed, but more than one jdk. They are from different vendors so I would not expect them to look for each other's classes. My default jdk is sun's 1.7.0_40.

**Comment by noisesmith** [comment] 2013-12-04 19:48
I added the following to the project.clj to debug:          

 :injections [(println "Using java version"
                        (System/getProperty "java.vendor")
                        (System/getProperty "java.version"))]

justin@fuckmonkey:~/clojure/schmetterling$  lein check
Using java version Oracle Corporation 1.7.0_40

**Comment by ghost** [comment] 2014-01-14 11:16
Same here. I have both java jdk and openjdk installed and they both have tools.jar available
yet lein can't find them.

Here's a workaround using `lein-localrepo` as a plugin:
in your (user/dev/etc') profile in ~/.lein/profiles.clj:

```
{ :plugins [[lein-localrepo "0.5.3"]]}
```

Followed by:

```
lein localrepo install PATH/TO/tools.jar foo/bar 0.1.0
```

Which puts the jar where lein can find it in ~/.m2.
Then add `[foo/bar "0.1.0"]` as a dependency to project.clj.

lein run and go.

**Comment by prismofeverything** [comment] 2014-01-14 18:40
I would love to find a general solution to this that we could post on the README.  @y-p : Do you think your solution will work in all cases?  I would rather find something that doesn't rely on a plugin.

So here is the question I pose to everyone:  What is the simplest way to provide tools.jar for people who have this issue?  If this is it, I will post it in the README.

**Comment by ghost** [comment] 2014-01-14 18:56
Since lein fetches plugins automatically that may actually be the path of least resistance.
[This](https://www.pgrs.net/2011/10/30/using-local-jars-with-leiningen/) manual recipe worked for older leins but not new leins. [This](https://gist.github.com/stuartsierra/3062743) recipe worked for me 
on latest lein but I didn't test on older lein. 

I know all this because I spent a couple of hours today chasing around the interwebs 
trying to figure out a way to get schmetterling going. You gotta do something.

Yes, I think the plugin route (ugly as it is) will work for everyone who has a tools.jar handy.

**Comment by prismofeverything** [comment] 2014-01-14 19:04
@y-p : Yeah, I appreciate your effort, and I agree that is probably the best way (at least, our current best way).  For some reason I am still puzzled as to why this happens in the first place.  What is special about tools.jar that it is sometimes not on the classpath?  

The problem is it only happens on certain machines, and not mine, so I have no way to investigate the problem myself.  I feel like if I understood the problem I could provide a solution from an informed perspective, but as it is I am working in the dark.  

Thanks again for tracking this down.

**Comment by noisesmith** [comment] 2014-01-14 19:09
It is a version issue. Java 7 does not include tools.jar in classpath by default, java 6 does. Try java 7 and you will get the bug. What we need is to figure out the portable way to make sure tools.jar is in the classpath regardless of (clojure compatible) jvm version.

**Comment by ghost** [comment] 2014-01-14 19:13
Exactly, and as far as I can tell after looking, the only way to get recent leins to put something
in the classpath is by declaring a dependency, which requires the jar to be in a local or remote 
maven repo.

**Comment by noisesmith** [comment] 2014-01-14 19:36
:source-paths ["src/clj" "/usr/lib/jvm/jdk1.7.0_40/lib/tools.jar"]

putting the above in project.clj makes it work for me. Perhaps we can do something like:

```
:source-paths ["src/clj" ~(System/getenv "TOOLS")]
```

and request that users export a usable path to tools.jar before running the app?

**Comment by noisesmith** [comment] 2014-01-14 19:42
Or we could hard code a relative path, and expect them to symlink or copy their own tools.jar into the project directory.

**Comment by prismofeverything** [comment] 2014-01-14 19:52
Aha!  So in both cases they need to find the path of their tools.jar, but one does not require a plugin.  

Let's add some variant of the ~(System/getenv "TOOLS") to the schmetterling project.clj and all they would have to do is export a variable that gives the path to their tools.jar.

**Comment by noisesmith** [comment] 2014-01-14 20:03
```
diff --git a/project.clj b/project.clj
index ed4b1f3..9f60ff6 100644
--- a/project.clj
+++ b/project.clj
@@ -15,7 +15,9 @@
                  [org.clojure/google-closure-library-third-party "0.0-2029"]]
   :plugins [[lein-cljsbuild "0.3.3"]]
   :source-paths ["src/clj"]
-  :resource-paths ["resources/"]
+  :resource-paths ~(if-let [tools (System/getenv "TOOLS_LIB_JAR")]
+                     ["resources" tools]
+                     ["resources"])
   :min-lein-version "2.0.0"
   :repl-options {:host "localhost"
                  :port 11911}
```

I am too lazy to make a fork right now and don't have rights to the repo to push a branch

**Comment by ghost** [comment] 2014-01-14 20:04
Yep, works for me too. much nicer.

**Comment by prismofeverything** [comment] 2014-01-15 00:03
Okay, instructions for this added to the README.  I also changed the env variable to JAVA_TOOLS_JAR.

Thank you @y-p and @noisesmith for helping out with this issue!

**Closed as completed by prismofeverything** 2014-01-15 00:03 UTC
